services:
  api:
    image: willianmfaria/puc_minas:flask
    container_name: api
    networks:
      - flasknetwork
    ports:
      - "8000:5000"
  
  web:
    image: willianmfaria/puc_minas:nginx
    container_name: web
    networks:
      - flasknetwork
    ports: 
      - "8001:80"
    depends_on:
      - "api"
    links:
      - "api:api"
networks:
  flasknetwork:
    driver: bridge