# -*- coding: utf-8 -*-
"""Preparação Dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14HdnP_gcIB--oPlT3emiAHe5nrEdMsB1
"""

from google.colab import files
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import geopandas as gpd
from sklearn.preprocessing import LabelEncoder

data = pd.read_csv ('heart_attack_prediction_dataset.csv')

# Deletar coluna ID
data = data.drop(columns=['Patient ID'])

# Dados duplicados e nulos

print(f"Total de linhas duplicadas: {data.duplicated().sum()}")
print("---------------")
print(f"Total Valores Nulos        : {data.isnull().sum().sum()}")

# Edição da Pressão Sanguinea

data["Systolic Pressure"] = data["Blood Pressure"].apply(lambda x: x.split("/")[0]).astype(int)
data["Dyastolic Pressure"] = data["Blood Pressure"].apply(lambda x: x.split("/")[1]).astype(int)

# Deletar Blood Pressure
data = data.drop(columns=['Blood Pressure'])

#Redução de casas decimais para uma após a vírgula

pd.set_option('display.precision', 1)

#Transformando dados de 'Diet'

ordinal_map = {'Healthy':2,'Average':1,'Unhealthy':0}
data['Diet'] = data['Diet'].map(ordinal_map)

#Transformando Male = 1 e Female = 0

ordinal_map_sex = {'Male':1, 'Female':0}
data['Sex'] = data['Sex'].map(ordinal_map_sex)

#Treinamento dos dados

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

y_train = y_train.values.reshape(-1, 1)
y_test = y_test.values.reshape(-1, 1)
y_test.shape